apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  minReadySeconds: 20
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: nginx
