apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-rs1
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: nginx
          env:
            - name: STRING
              value: "hai"
