apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-rs1
  annotations:
    kubernetes.io/change-cause: "deploying v2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: nginx
