apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  restartPolicy: OnFailure
  containers:
    - name: myapp
      image: vinsdocker/k8s-pod-assignment
      env:
        - name: NUMBER
          value: "5"
      args:
        - "MY_ARG"
