apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rs1
  labels:
    key: my-rs1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx-1
          image: nginx

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rs2
  labels:
    key: my-rs2
spec:
  replicas: 2
  selector:
    matchLabels:
      aoo: vae
  template:
    metadata:
      labels:
        aoo: vae
    spec:
      containers:
        - name: nginx-2
          image: nginx
